[recorder]
enable = true
simulate = true
history_seconds = 4
codec = "XVID"
file_ext = "avi"

[ntfy]
url = "https://ntfy.sh"
topic = "NTFY_TOPIC_URL"

[camera]
color_image_size = [ 1920, 1080,]
lores_image_size = [ 640, 360,]
fps = 5

[vision]
debug = true

[camera.picamera2]
ISO = 100

[camera.dummy_camera]
dummy_data_subfolder = "gardenBird1_vid_cropped"
speed_factor = 1

[vision.motion_detector.activity_map]
cell_size = [ 10, 10,]
alpha = 0.05
alpha_warmup = 0.05
