# Code generated by ChatGPT
"""
Tool: TKinter GUI to extract video frames as images

Usage:
- Open a video file -> Details like resolution and FPS are shown
  and the fields for resolution, start and end frame are filled automatically
- If needed, alter the target resolution of the extracted frames (rescale)
- If needed, alter start and end frame number for the extraction (first frame is 0)
- Set a frame skip, if only each n-th frame shall be extracted (default: 1)
- Click the "Start export" button, select a target folder and wait until
  all images have been extracted to this folder
"""

import os
from pathlib import Path
import tkinter as tk
from tkinter import filedialog, messagebox, ttk

import cv2


VIDEO_FILETYPES = [
    ("Video files", "*.mp4 *.avi *.mov *.mkv *.m4v"),
    ("MP4 files", "*.mp4"),
    ("AVI files", "*.avi"),
    ("All files", "*.*"),
]


class VideoFrameExtractorApp:
    def __init__(self, root: tk.Tk) -> None:
        self.root = root
        self.root.title("Video Frame Extractor")
        self.root.geometry("840x420")
        self.root.minsize(760, 320)
        self.root.configure(bg="#f3f4f6")

        self.video_path: Path | None = None
        self.total_frames: int = 0
        self.fps: float = 0.0
        self.video_width: int = 0
        self.video_height: int = 0

        self._configure_style()
        self._build_ui()

    def _configure_style(self) -> None:
        style = ttk.Style()
        try:
            style.theme_use("clam")
        except tk.TclError:
            pass

        self.root.option_add("*Font", "TkDefaultFont 10")
        style.configure("App.TFrame", background="#f3f4f6")
        style.configure("Card.TLabelframe", background="#f3f4f6", borderwidth=1, relief="solid")
        style.configure("Card.TLabelframe.Label", background="#f3f4f6", foreground="#111827", font=("TkDefaultFont", 10, "bold"))
        style.configure("TLabel", background="#f3f4f6", foreground="#111827")
        style.configure("Muted.TLabel", background="#f3f4f6", foreground="#4b5563")
        style.configure("TButton", padding=(10, 6))
        style.configure("TEntry", padding=6)
        style.configure("TProgressbar", thickness=14)
        style.configure("Status.TLabel", background="#e5e7eb", foreground="#111827", padding=(10, 8))

    def _build_ui(self) -> None:
        self.root.rowconfigure(0, weight=1)
        self.root.columnconfigure(0, weight=1)

        main = ttk.Frame(self.root, padding=16, style="App.TFrame")
        main.grid(row=0, column=0, sticky="nsew")
        main.columnconfigure(0, weight=1)

        content = ttk.Frame(main, style="App.TFrame")
        content.grid(row=0, column=0, sticky="nsew")
        content.columnconfigure(0, weight=1)
        content.columnconfigure(1, weight=1)

        row = 0

        file_frame = ttk.LabelFrame(content, text="Video", padding=12, style="Card.TLabelframe")
        file_frame.grid(row=row, column=0, columnspan=2, sticky="ew", pady=(0, 12))
        file_frame.columnconfigure(1, weight=1)

        ttk.Label(file_frame, text="Video file:").grid(row=0, column=0, sticky="w", pady=4)
        self.video_path_var = tk.StringVar()
        ttk.Entry(file_frame, textvariable=self.video_path_var, state="readonly").grid(
            row=0, column=1, sticky="ew", padx=(8, 10), pady=4
        )
        ttk.Button(file_frame, text="Select...", command=self.select_video).grid(row=0, column=2, sticky="e", pady=4)

        row += 1
        info_frame = ttk.LabelFrame(content, text="Video info", padding=12, style="Card.TLabelframe")
        info_frame.grid(row=row, column=0, sticky="nsew", padx=(0, 6), pady=(0, 12))
        info_frame.columnconfigure(1, weight=1)

        self.frames_var = tk.StringVar(value="-")
        self.fps_var = tk.StringVar(value="-")
        self.video_res_var = tk.StringVar(value="-")

        ttk.Label(info_frame, text="Frames:", style="Muted.TLabel").grid(row=0, column=0, sticky="w", pady=4)
        ttk.Label(info_frame, textvariable=self.frames_var).grid(row=0, column=1, sticky="w", padx=(8, 0), pady=4)

        ttk.Label(info_frame, text="FPS:", style="Muted.TLabel").grid(row=1, column=0, sticky="w", pady=4)
        ttk.Label(info_frame, textvariable=self.fps_var).grid(row=1, column=1, sticky="w", padx=(8, 0), pady=4)

        ttk.Label(info_frame, text="Resolution:", style="Muted.TLabel").grid(row=2, column=0, sticky="w", pady=4)
        ttk.Label(info_frame, textvariable=self.video_res_var).grid(row=2, column=1, sticky="w", padx=(8, 0), pady=4)

        settings_frame = ttk.LabelFrame(content, text="Export settings", padding=12, style="Card.TLabelframe")
        settings_frame.grid(row=row, column=1, sticky="nsew", padx=(6, 0), pady=(0, 12))
        settings_frame.columnconfigure(1, weight=1)
        settings_frame.columnconfigure(3, weight=1)

        self.target_width_var = tk.StringVar(value="640")
        self.target_height_var = tk.StringVar(value="360")
        self.start_frame_var = tk.StringVar(value="0")
        self.end_frame_var = tk.StringVar(value="0")
        self.frame_skip_var = tk.StringVar(value="1")
        self.jpg_quality_var = tk.StringVar(value="95")

        ttk.Label(settings_frame, text="Target width:", style="Muted.TLabel").grid(row=0, column=0, sticky="w", pady=4)
        ttk.Entry(settings_frame, textvariable=self.target_width_var, width=12).grid(row=0, column=1, sticky="ew", padx=(8, 16), pady=4)

        ttk.Label(settings_frame, text="Target height:", style="Muted.TLabel").grid(row=0, column=2, sticky="w", pady=4)
        ttk.Entry(settings_frame, textvariable=self.target_height_var, width=12).grid(row=0, column=3, sticky="ew", padx=(8, 0), pady=4)

        ttk.Label(settings_frame, text="Start frame:", style="Muted.TLabel").grid(row=1, column=0, sticky="w", pady=4)
        ttk.Entry(settings_frame, textvariable=self.start_frame_var, width=12).grid(row=1, column=1, sticky="ew", padx=(8, 16), pady=4)

        ttk.Label(settings_frame, text="End frame:", style="Muted.TLabel").grid(row=1, column=2, sticky="w", pady=4)
        ttk.Entry(settings_frame, textvariable=self.end_frame_var, width=12).grid(row=1, column=3, sticky="ew", padx=(8, 0), pady=4)

        ttk.Label(settings_frame, text="Frame skip:", style="Muted.TLabel").grid(row=2, column=0, sticky="w", pady=4)
        ttk.Entry(settings_frame, textvariable=self.frame_skip_var, width=12).grid(row=2, column=1, sticky="ew", padx=(8, 16), pady=4)

        ttk.Label(settings_frame, text="JPG quality:", style="Muted.TLabel").grid(row=2, column=2, sticky="w", pady=4)
        ttk.Entry(settings_frame, textvariable=self.jpg_quality_var, width=12).grid(row=2, column=3, sticky="ew", padx=(8, 0), pady=4)

        row += 1
        footer = ttk.Frame(main, style="App.TFrame")
        footer.grid(row=1, column=0, sticky="ew")
        footer.columnconfigure(0, weight=1)

        self.status_var = tk.StringVar(value="Select a video file.")
        ttk.Label(footer, textvariable=self.status_var, anchor="w", style="Status.TLabel").grid(
            row=0, column=0, sticky="ew", pady=(0, 10)
        )

        self.progress = ttk.Progressbar(footer, mode="determinate")
        self.progress.grid(row=1, column=0, sticky="ew")

        ttk.Button(footer, text="Start export", command=self.start_export).grid(row=2, column=0, sticky="e", pady=(12, 0))

    def select_video(self) -> None:
        path = filedialog.askopenfilename(title="Select video file", filetypes=VIDEO_FILETYPES)
        if not path:
            return

        self.video_path = Path(path)
        self.video_path_var.set(str(self.video_path))
        self._load_video_info()

    def _load_video_info(self) -> None:
        if self.video_path is None:
            return

        cap = cv2.VideoCapture(str(self.video_path))
        if not cap.isOpened():
            messagebox.showerror("Error", "Could not open video file.")
            self._clear_video_info()
            return

        total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        fps = float(cap.get(cv2.CAP_PROP_FPS))
        width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        cap.release()

        self.total_frames = max(total_frames, 0)
        self.fps = fps if fps > 0 else 0.0
        self.video_width = max(width, 0)
        self.video_height = max(height, 0)

        self.frames_var.set(str(self.total_frames))
        self.fps_var.set(f"{self.fps:.3f}" if self.fps > 0 else "unknown")
        self.video_res_var.set(f"{self.video_width} x {self.video_height}")

        self.target_width_var.set(str(self.video_width))
        self.target_height_var.set(str(self.video_height))

        if self.total_frames > 0:
            self.start_frame_var.set("0")
            self.end_frame_var.set(str(self.total_frames - 1))

        self.status_var.set("Video loaded.")

    def _clear_video_info(self) -> None:
        self.video_path = None
        self.total_frames = 0
        self.fps = 0.0
        self.video_width = 0
        self.video_height = 0
        self.video_path_var.set("")
        self.frames_var.set("-")
        self.fps_var.set("-")
        self.video_res_var.set("-")
        self.status_var.set("Select a video file.")

    def start_export(self) -> None:
        if self.video_path is None:
            messagebox.showwarning("Missing video", "Please select a video file first.")
            return

        try:
            target_width = int(self.target_width_var.get())
            target_height = int(self.target_height_var.get())
            start_frame = int(self.start_frame_var.get())
            end_frame = int(self.end_frame_var.get())
            frame_skip = int(self.frame_skip_var.get())
            jpg_quality = int(self.jpg_quality_var.get())
        except ValueError:
            messagebox.showerror("Invalid input", "Please enter valid integer values.")
            return

        if target_width <= 0 or target_height <= 0:
            messagebox.showerror("Invalid resolution", "Target width and height must be > 0.")
            return

        if self.total_frames <= 0:
            messagebox.showerror("Invalid video", "The video does not report a valid frame count.")
            return

        if start_frame < 0 or end_frame < 0 or start_frame > end_frame:
            messagebox.showerror("Invalid frame interval", "Please use a valid frame interval.")
            return

        if end_frame >= self.total_frames:
            messagebox.showerror(
                "Invalid frame interval",
                f"End frame must be <= {self.total_frames - 1}."
            )
            return

        if frame_skip <= 0:
            messagebox.showerror("Invalid frame skip", "Frame skip must be >= 1.")
            return

        if not (1 <= jpg_quality <= 100):
            messagebox.showerror("Invalid JPG quality", "JPG quality must be between 1 and 100.")
            return

        output_dir = filedialog.askdirectory(title="Select output folder")
        if not output_dir:
            return

        success, saved_count = self._export_frames(
            output_dir=Path(output_dir),
            start_frame=start_frame,
            end_frame=end_frame,
            frame_skip=frame_skip,
            target_width=target_width,
            target_height=target_height,
            jpg_quality=jpg_quality,
        )

        if success:
            self.status_var.set(f"Done. Saved {saved_count} frames.")
            messagebox.showinfo("Finished", f"Saved {saved_count} frames to {output_dir}.")

    def _export_frames(
        self,
        output_dir: Path,
        start_frame: int,
        end_frame: int,
        frame_skip: int,
        target_width: int,
        target_height: int,
        jpg_quality: int,
    ) -> tuple[bool, int]:
        assert self.video_path is not None

        output_dir.mkdir(parents=True, exist_ok=True)

        cap = cv2.VideoCapture(str(self.video_path))
        if not cap.isOpened():
            messagebox.showerror("Error", "Could not open video file for export.")
            return False, 0

        frame_indices = list(range(start_frame, end_frame + 1, frame_skip))
        total_to_save = len(frame_indices)
        if total_to_save == 0:
            cap.release()
            messagebox.showwarning("No frames", "The selected interval does not contain any frames.")
            return False, 0

        digits = max(1, len(str(max(self.total_frames - 1, 0))))
        base_name = self.video_path.stem

        self.progress.configure(maximum=total_to_save, value=0)
        self.root.update_idletasks()

        saved_count = 0

        try:
            for idx, frame_number in enumerate(frame_indices, start=1):
                cap.set(cv2.CAP_PROP_POS_FRAMES, frame_number)
                ok, frame = cap.read()
                if not ok or frame is None:
                    self.status_var.set(f"Warning: could not read frame {frame_number}. Skipping.")
                    self.root.update_idletasks()
                    continue

                resized = self._resize_with_letterbox(frame, target_width, target_height)
                out_name = f"{base_name}_{frame_number:0{digits}d}.jpg"
                out_path = output_dir / out_name

                write_ok = cv2.imwrite(
                    str(out_path),
                    resized,
                    [cv2.IMWRITE_JPEG_QUALITY, jpg_quality],
                )
                if not write_ok:
                    raise RuntimeError(f"Could not write file: {out_path}")

                saved_count += 1
                self.progress.configure(value=idx)
                self.status_var.set(f"Saving frame {frame_number} ({idx}/{total_to_save})")
                self.root.update_idletasks()
        except Exception as exc:
            cap.release()
            messagebox.showerror("Export error", str(exc))
            return False, saved_count

        cap.release()
        self.progress.configure(value=total_to_save)
        return True, saved_count

    @staticmethod
    def _resize_with_letterbox(frame, target_width: int, target_height: int):
        src_height, src_width = frame.shape[:2]
        if src_width <= 0 or src_height <= 0:
            raise ValueError("Invalid source frame size.")

        scale = min(target_width / src_width, target_height / src_height)
        new_width = max(1, int(round(src_width * scale)))
        new_height = max(1, int(round(src_height * scale)))

        interpolation = cv2.INTER_AREA if scale < 1.0 else cv2.INTER_LINEAR
        resized = cv2.resize(frame, (new_width, new_height), interpolation=interpolation)

        canvas = cv2.copyMakeBorder(
            resized,
            top=(target_height - new_height) // 2,
            bottom=target_height - new_height - (target_height - new_height) // 2,
            left=(target_width - new_width) // 2,
            right=target_width - new_width - (target_width - new_width) // 2,
            borderType=cv2.BORDER_CONSTANT,
            value=(0, 0, 0),
        )
        return canvas


def main() -> None:
    root = tk.Tk()
    app = VideoFrameExtractorApp(root)
    root.mainloop()


if __name__ == "__main__":
    main()
