# Code base generated by Mistral
"""
Tool: Process input images (video frames) and generate a background
      image using the median method and MOG2 ('removal' of dynamic objects)

Usage:
- Hard-code the path to the input images (INPUT_DIR) and the names of
  the result images (output_file_median and output_file_MOG2) below and
  execute the script
"""

import cv2
import numpy as np

from bird_guard.utils import PlatformInfo

DATA_PATH = PlatformInfo.get_data_path("bird_guard")

# Input image dir
IMAGE_DIR = DATA_PATH / "dummy_images/ducks_5fps/"

# Result images
output_file_median = IMAGE_DIR.parents[0] / "ducks_5fps_background_median.jpg"
output_file_MOG2   = IMAGE_DIR.parents[0] / "ducks_5fps_background_MOG2.jpg"

# -------------

print("Gathering images ...")
images = [cv2.imread(path) for path in sorted(IMAGE_DIR.glob("*.jpg"))]

print("Generating median image ...")
median_background = np.median(images, axis=0).astype("uint8")
cv2.imwrite(output_file_median, median_background)
print(f"Saved median result to: {output_file_median}")


print("Generating MOG2 image ...")
back_sub = cv2.createBackgroundSubtractorMOG2(history=500, varThreshold=16, detectShadows=False)

background = None

for frame in images:

    fg_mask = back_sub.apply(frame)

    if background is None:
        background = frame.copy().astype(float)
    else:
        background = cv2.accumulateWeighted(frame.astype(float), background, alpha=0.01)

cv2.imwrite(output_file_MOG2, background.astype("uint8"))
print(f"Saved MOG2 result to: {output_file_MOG2}")

print("FINISHED")