# Code generated by ChatGPT (using bird_guard classes; manual adjustments/extensions)
"""
Tool: TKinter GUI to extract a subsection of an input video and/or crop the image and/or change the FPS

Usage:
- Open a video file -> Details like number of frames and FPS are shown
- Use the Play/Pause button to play the video (unfortunately not in realtime, this was not the goal)
  or use the horizontal scroll bar to scrub through the video
- Use the 'Set as Start/End Frame' buttons or the corresponding text fields to define a subsection of the video
- If needed, select a different target FPS value (must be a divisor of the original video FPS)
- If needed, enable the crop feature and define a subsection of the image (use the Lock Aspect check box to alter/keep
  the aspect ratio of the crop box). The crop box size can be changed by the mouse wheel or the handles at the box
  corners (in lock aspect mode) or the box edges (lock aspect disabled). The box can be dragged around with the left
  mouse button
- Click 'Save Video As' to export the cropped video section with altered FPS to a new file
- Click 'Save Current Frame' to export the current cropped frame (will be stored next to the video as jpg with the frame
  number as filename suffix)
"""

from __future__ import annotations

import math
import time
import tkinter as tk
from dataclasses import dataclass
from pathlib import Path
from tkinter import filedialog, messagebox, ttk
from typing import Optional

import cv2
import numpy as np
from PIL import Image, ImageTk

from bird_guard.camera.camera import Frame
from bird_guard.config import ConfigHandler
from bird_guard.main import APP_NAME
from bird_guard.recorder import VideoRecorder
from bird_guard.utils import PlatformInfo, VideoPlayer
from bird_guard.vision.utils.image_utils import BGRImage


@dataclass
class CropBox:
    left: int
    top: int
    width: int
    height: int

    @property
    def right(self) -> int:
        return self.left + self.width

    @property
    def bottom(self) -> int:
        return self.top + self.height

    @property
    def aspect_ratio(self) -> float:
        return self.width / self.height if self.height else 0.0


class VideoCropExportGui(tk.Tk):
    MIN_CROP_SIZE = 32
    HANDLE_SIZE_SCREEN = 10
    CROP_COLOR = "#90ff90"

    def __init__(self) -> None:
        super().__init__()

        self.title("Bird Guard Video Crop Export")
        self.state("zoomed")

        self._settings = self._load_settings()
        self._last_open_dir = PlatformInfo.get_data_path(APP_NAME)

        self._video_path: Optional[Path] = None
        self._player: Optional[VideoPlayer] = None
        self._input_fps: Optional[float] = None
        self._target_fps: Optional[int] = None
        self._frame_skip: int = 1
        self._num_frames: int = 0
        self._current_frame_index: int = 0
        self._start_frame: int = 0
        self._end_frame: int = 0
        self._last_frame_bgr: Optional[BGRImage] = None
        self._last_frame_for_display_bgr: Optional[BGRImage] = None

        self._playing = False
        self._play_after_id: Optional[str] = None
        self._scrubbing = False
        self._updating_slider = False
        self._exporting = False

        self._display_scale = 1.0
        self._display_offset_x = 0
        self._display_offset_y = 0
        self._display_width = 0
        self._display_height = 0
        self._tk_image: Optional[ImageTk.PhotoImage] = None

        self._crop_enabled = tk.BooleanVar(value=False)
        self._lock_aspect = tk.BooleanVar(value=True)
        self._crop_box: Optional[CropBox] = None
        self._drag_mode: Optional[str] = None
        self._drag_start_mouse_video: Optional[tuple[int, int]] = None
        self._drag_start_crop: Optional[CropBox] = None

        self._build_ui()
        self._bind_events()
        self._update_status()

    def _load_settings(self):
        config_handler = ConfigHandler(PlatformInfo.get_config_path(APP_NAME) / "config.toml")
        settings = config_handler.get_config()
        settings.recorder.enable = True
        settings.recorder.simulate = False
        return settings

    def _build_ui(self) -> None:
        self.rowconfigure(0, weight=1)
        self.columnconfigure(0, weight=1)

        self.canvas = tk.Canvas(self, bg="black", highlightthickness=0)
        self.canvas.grid(row=0, column=0, sticky="nsew")

        self.slider_canvas = tk.Canvas(self, height=34, bg="#222222", highlightthickness=0)
        self.slider_canvas.grid(row=1, column=0, sticky="ew")

        status_frame = ttk.Frame(self)
        status_frame.grid(row=2, column=0, sticky="ew", padx=6, pady=(4, 2))

        self.status_text = tk.StringVar(value="No video loaded")
        self.crop_text = tk.StringVar(value="Crop: -")

        ttk.Label(status_frame, textvariable=self.status_text).pack(side="left", padx=(0, 18))
        ttk.Label(status_frame, textvariable=self.crop_text).pack(side="left")

        range_frame = ttk.Frame(self)
        range_frame.grid(row=3, column=0, sticky="ew", padx=6, pady=2)

        ttk.Label(range_frame, text="Start:").pack(side="left")
        self.start_entry = ttk.Entry(range_frame, width=10)
        self.start_entry.pack(side="left", padx=(3, 10))

        ttk.Label(range_frame, text="End:").pack(side="left")
        self.end_entry = ttk.Entry(range_frame, width=10)
        self.end_entry.pack(side="left", padx=(3, 10))

        ttk.Button(range_frame, text="Apply Range", command=self._apply_range_entries).pack(side="left")

        controls = ttk.Frame(self)
        controls.grid(row=4, column=0, sticky="ew", padx=6, pady=(2, 6))

        ttk.Button(controls, text="Open Video", command=self._open_video_dialog).pack(side="left", padx=(0, 6))

        self.play_button = ttk.Button(controls, text="Play", command=self._toggle_play)
        self.play_button.pack(side="left", padx=(0, 24))

        self.crop_button = ttk.Checkbutton(
            controls,
            text="Enable Crop",
            variable=self._crop_enabled,
            command=self._on_crop_enabled_changed,
        )
        self.crop_button.pack(side="left", padx=(0, 6))

        self.aspect_checkbox = ttk.Checkbutton(
            controls,
            text="Lock Aspect",
            variable=self._lock_aspect,
            command=self._on_lock_aspect_changed,
        )
        self.aspect_checkbox.pack(side="left", padx=(0, 12))

        ttk.Button(controls, text="Set as Start Frame", command=self._set_start_frame).pack(side="left", padx=(0, 6))
        ttk.Button(controls, text="Set as End Frame", command=self._set_end_frame).pack(side="left", padx=(0, 16))

        ttk.Label(controls, text="Target FPS:").pack(side="left")
        self.target_fps_combo = ttk.Combobox(controls, width=8, state="readonly")
        self.target_fps_combo.pack(side="left", padx=(4, 16))
        self.target_fps_combo.bind("<<ComboboxSelected>>", self._on_target_fps_changed)

        ttk.Button(controls, text="Save Video As", command=self._save_as).pack(side="left", padx=(0, 6))
        ttk.Button(controls, text="Save Current Frame", command=self._save_current_frame).pack(side="left", padx=(0, 16))

    def _bind_events(self) -> None:
        self.canvas.bind("<Configure>", lambda event: self._redraw())
        self.canvas.bind("<ButtonPress-1>", self._on_canvas_mouse_down)
        self.canvas.bind("<B1-Motion>", self._on_canvas_mouse_drag)
        self.canvas.bind("<ButtonRelease-1>", self._on_canvas_mouse_up)
        self.canvas.bind("<MouseWheel>", self._on_canvas_mouse_wheel)
        self.canvas.bind("<Button-4>", self._on_canvas_mouse_wheel)
        self.canvas.bind("<Button-5>", self._on_canvas_mouse_wheel)

        self.slider_canvas.bind("<Configure>", lambda event: self._draw_slider())
        self.slider_canvas.bind("<ButtonPress-1>", self._on_slider_mouse_down)
        self.slider_canvas.bind("<B1-Motion>", self._on_slider_mouse_drag)
        self.slider_canvas.bind("<ButtonRelease-1>", self._on_slider_mouse_up)

        self.start_entry.bind("<Return>", lambda event: self._apply_range_entries())
        self.end_entry.bind("<Return>", lambda event: self._apply_range_entries())

    def _open_video_dialog(self) -> None:
        video_path = filedialog.askopenfilename(
            title="Open video",
            filetypes=[("Video files", "*.mp4 *.avi *.mkv *.mov"), ("All files", "*.*")],
            initialdir=self._last_open_dir
        )
        if not video_path:
            return

        self._last_open_dir = Path(video_path).parent
        self._open_video(Path(video_path))

    def _open_video(self, video_path: Path) -> None:
        self._pause()
        self._close_player()

        self._video_path = video_path
        self._input_fps = self._read_video_fps(video_path)
        self._target_fps = int(round(self._input_fps)) if self._input_fps else None
        self._player = VideoPlayer(video_path, target_fps=self._target_fps)

        num_frames = self._player.get_num_frames()
        if num_frames is None:
            raise RuntimeError("VideoPlayer.get_num_frames() returned None.")

        self._num_frames = int(num_frames)
        self._start_frame = 0
        self._end_frame = max(0, self._num_frames - 1)
        self._current_frame_index = 0

        self._init_target_fps_options()
        self._read_frame_at(0)
        self._init_crop_box_full_frame()
        self._update_range_entries()
        self._update_status()
        self._draw_slider()
        self._redraw()

    def _read_video_fps(self, video_path: Path) -> float:
        cap = cv2.VideoCapture(str(video_path))
        try:
            fps = cap.get(cv2.CAP_PROP_FPS)
            if fps is None or fps <= 0:
                return 25.0
            return float(fps)
        finally:
            cap.release()

    def _init_target_fps_options(self) -> None:
        if not self._input_fps:
            values = [25, 5, 1]
        else:
            input_fps_int = int(round(self._input_fps))
            values = [fps for fps in range(input_fps_int, 0, -1) if input_fps_int % fps == 0]

        self.target_fps_combo["values"] = values
        if values:
            self._target_fps = values[0]
            self.target_fps_combo.set(str(values[0]))
        self._update_frame_skip()

    def _update_frame_skip(self) -> None:
        if not self._input_fps or not self._target_fps:
            self._frame_skip = 1
            return
        self._frame_skip = max(1, int(round(self._input_fps / self._target_fps)))

    def _on_target_fps_changed(self, event=None) -> None:
        value = self.target_fps_combo.get()
        if not value:
            return
        self._target_fps = int(value)
        self._update_frame_skip()
        self._reopen_player_keep_position()
        self._update_status()

    def _reopen_player_keep_position(self) -> None:
        if not self._video_path:
            return
        frame_index = self._current_frame_index
        self._close_player()
        self._player = VideoPlayer(self._video_path, target_fps=self._target_fps)
        self._read_frame_at(frame_index)

    def _close_player(self) -> None:
        if self._player is not None:
            self._player.close()
            self._player = None

    def _read_frame_at(self, frame_index: int) -> Optional[BGRImage]:
        if self._player is None:
            return None

        frame_index = self._clamp_frame_index(frame_index)
        self._player.set_current_frame_index(frame_index)
        frame = self._player.get_next_frame()

        self._current_frame_index = frame_index
        self._last_frame_bgr = frame
        self._last_frame_for_display_bgr = frame
        return frame

    def _read_next_playback_frame(self) -> Optional[BGRImage]:
        if self._player is None:
            return None

        next_index = self._current_frame_index + self._frame_skip
        if next_index > self._end_frame:
            return None

        frame = self._player.get_next_frame()
        self._current_frame_index = next_index
        self._last_frame_bgr = frame
        self._last_frame_for_display_bgr = frame
        return frame

    def _clamp_frame_index(self, frame_index: int) -> int:
        if self._num_frames <= 0:
            return 0
        return max(0, min(int(frame_index), self._num_frames - 1))

    def _toggle_play(self) -> None:
        if self._playing:
            self._pause()
        else:
            self._play()

    def _play(self) -> None:
        if self._player is None or self._num_frames <= 0:
            return

        if self._current_frame_index >= self._end_frame:
            self._read_frame_at(self._start_frame)

        self._player.set_current_frame_index(self._current_frame_index + self._frame_skip)
        self._playing = True
        self.play_button.config(text="Pause")
        self._schedule_next_playback_frame()

    def _pause(self) -> None:
        self._playing = False
        self.play_button.config(text="Play")
        if self._play_after_id is not None:
            self.after_cancel(self._play_after_id)
            self._play_after_id = None

    def _schedule_next_playback_frame(self) -> None:
        if not self._playing:
            return

        if not self._target_fps:
            delay_ms = 40
        else:
            delay_ms = max(1, int(1000 / self._target_fps))

        self._play_after_id = self.after(delay_ms, self._playback_step)

    def _playback_step(self) -> None:
        self._play_after_id = None

        if not self._playing:
            return

        frame = self._read_next_playback_frame()
        if frame is None:
            self._pause()
            return

        self._redraw()
        self._draw_slider()
        self._update_status()
        self._schedule_next_playback_frame()

    def _on_slider_mouse_down(self, event) -> None:
        self._pause()
        self._scrubbing = True
        self._scrub_to_mouse_x(event.x)

    def _on_slider_mouse_drag(self, event) -> None:
        if not self._scrubbing:
            return
        self._scrub_to_mouse_x(event.x)

    def _on_slider_mouse_up(self, event) -> None:
        self._scrubbing = False
        self._scrub_to_mouse_x(event.x)

    def _scrub_to_mouse_x(self, x: int) -> None:
        if self._num_frames <= 0:
            return

        width = max(1, self.slider_canvas.winfo_width())
        t = max(0.0, min(1.0, x / width))
        frame_index = int(round(t * (self._num_frames - 1)))
        self._read_frame_at(frame_index)
        self._redraw()
        self._draw_slider()
        self._update_status()

    def _draw_slider(self) -> None:
        c = self.slider_canvas
        c.delete("all")

        width = max(1, c.winfo_width())
        height = max(1, c.winfo_height())

        c.create_rectangle(0, height // 2 - 3, width, height // 2 + 3, fill="#666666", outline="")

        if self._num_frames <= 1:
            return

        def x_for_frame(frame_index: int) -> int:
            return int(round((frame_index / (self._num_frames - 1)) * width))

        start_x = x_for_frame(self._start_frame)
        end_x = x_for_frame(self._end_frame)
        current_x = x_for_frame(self._current_frame_index)

        c.create_rectangle(start_x, height // 2 - 5, end_x, height // 2 + 5, fill="#3f5f3f", outline="")
        c.create_line(start_x, 2, start_x, height - 2, fill="#90ff90", width=2)
        c.create_line(end_x, 2, end_x, height - 2, fill="#ff9090", width=2)
        c.create_oval(current_x - 7, height // 2 - 7, current_x + 7, height // 2 + 7, fill="#dddddd", outline="#ffffff")

    def _update_range_entries(self) -> None:
        self.start_entry.delete(0, tk.END)
        self.start_entry.insert(0, str(self._start_frame))
        self.end_entry.delete(0, tk.END)
        self.end_entry.insert(0, str(self._end_frame))

    def _apply_range_entries(self) -> None:
        if self._num_frames <= 0:
            return
        try:
            start = int(self.start_entry.get())
            end = int(self.end_entry.get())
        except ValueError:
            messagebox.showerror("Invalid range", "Start and end frame must be integers.")
            self._update_range_entries()
            return

        start = self._clamp_frame_index(start)
        end = self._clamp_frame_index(end)
        if start > end:
            start, end = end, start

        self._start_frame = start
        self._end_frame = end
        self._update_range_entries()
        self._draw_slider()
        self._update_status()

    def _set_start_frame(self) -> None:
        self._start_frame = min(self._current_frame_index, self._end_frame)
        self._update_range_entries()
        self._draw_slider()
        self._update_status()

    def _set_end_frame(self) -> None:
        self._end_frame = max(self._current_frame_index, self._start_frame)
        self._update_range_entries()
        self._draw_slider()
        self._update_status()

    def _on_crop_enabled_changed(self) -> None:
        if self._crop_enabled.get() and self._crop_box is None:
            self._init_crop_box_full_frame()
        self._redraw()
        self._update_status()

    def _on_lock_aspect_changed(self) -> None:
        self._redraw()
        self._update_status()

    def _init_crop_box_full_frame(self) -> None:
        if self._last_frame_bgr is None:
            self._crop_box = None
            return
        frame_h, frame_w = self._last_frame_bgr.shape[:2]
        self._crop_box = CropBox(0, 0, frame_w, frame_h)

    def _clamp_crop_box(self, box: CropBox) -> CropBox:
        if self._last_frame_bgr is None:
            return box

        frame_h, frame_w = self._last_frame_bgr.shape[:2]
        width = max(self.MIN_CROP_SIZE, min(box.width, frame_w))
        height = max(self.MIN_CROP_SIZE, min(box.height, frame_h))
        left = max(0, min(box.left, frame_w - width))
        top = max(0, min(box.top, frame_h - height))
        return CropBox(left, top, width, height)

    def _screen_to_video(self, sx: int, sy: int) -> Optional[tuple[int, int]]:
        if self._last_frame_bgr is None or self._display_width <= 0 or self._display_height <= 0:
            return None

        x = sx - self._display_offset_x
        y = sy - self._display_offset_y
        if x < 0 or y < 0 or x >= self._display_width or y >= self._display_height:
            return None

        video_x = int(round(x / self._display_scale))
        video_y = int(round(y / self._display_scale))
        frame_h, frame_w = self._last_frame_bgr.shape[:2]
        video_x = max(0, min(video_x, frame_w - 1))
        video_y = max(0, min(video_y, frame_h - 1))
        return video_x, video_y

    def _video_to_screen(self, vx: int, vy: int) -> tuple[int, int]:
        sx = int(round(self._display_offset_x + vx * self._display_scale))
        sy = int(round(self._display_offset_y + vy * self._display_scale))
        return sx, sy

    def _on_canvas_mouse_down(self, event) -> None:
        if not self._crop_enabled.get() or self._crop_box is None:
            return

        pos = self._screen_to_video(event.x, event.y)
        if pos is None:
            return

        self._drag_mode = self._hit_test_crop(pos)
        self._drag_start_mouse_video = pos
        self._drag_start_crop = CropBox(
            self._crop_box.left,
            self._crop_box.top,
            self._crop_box.width,
            self._crop_box.height,
        )

    def _on_canvas_mouse_drag(self, event) -> None:
        if not self._crop_enabled.get() or self._crop_box is None:
            return
        if self._drag_mode is None or self._drag_start_mouse_video is None or self._drag_start_crop is None:
            return

        pos = self._screen_to_video(event.x, event.y)
        if pos is None:
            return

        dx = pos[0] - self._drag_start_mouse_video[0]
        dy = pos[1] - self._drag_start_mouse_video[1]
        start = self._drag_start_crop

        if self._drag_mode == "move":
            new_box = CropBox(start.left + dx, start.top + dy, start.width, start.height)
        else:
            new_box = self._resize_crop_box_by_handle(start, self._drag_mode, dx, dy)

        self._crop_box = self._clamp_crop_box(new_box)
        self._redraw()
        self._update_status()

    def _on_canvas_mouse_up(self, event) -> None:
        self._drag_mode = None
        self._drag_start_mouse_video = None
        self._drag_start_crop = None

    def _on_canvas_mouse_wheel(self, event) -> None:
        if not self._crop_enabled.get() or self._crop_box is None or self._last_frame_bgr is None:
            return

        if event.num == 4 or getattr(event, "delta", 0) > 0:
            factor = 1.08
        else:
            factor = 1 / 1.08

        old = self._crop_box
        center_x = old.left + old.width / 2
        center_y = old.top + old.height / 2

        if self._lock_aspect.get():
            aspect = old.aspect_ratio if old.aspect_ratio > 0 else 1.0
            new_w = int(round(old.width * factor))
            new_h = int(round(new_w / aspect))
        else:
            new_w = int(round(old.width * factor))
            new_h = int(round(old.height * factor))

        new_w = max(self.MIN_CROP_SIZE, new_w)
        new_h = max(self.MIN_CROP_SIZE, new_h)
        new_box = CropBox(int(round(center_x - new_w / 2)), int(round(center_y - new_h / 2)), new_w, new_h)

        self._crop_box = self._clamp_crop_box(new_box)
        self._redraw()
        self._update_status()

    def _hit_test_crop(self, pos: tuple[int, int]) -> Optional[str]:
        if self._crop_box is None:
            return None

        x, y = pos
        box = self._crop_box
        handle_radius_video = max(4, int(round(self.HANDLE_SIZE_SCREEN / max(self._display_scale, 0.001))))

        near_left = abs(x - box.left) <= handle_radius_video
        near_right = abs(x - box.right) <= handle_radius_video
        near_top = abs(y - box.top) <= handle_radius_video
        near_bottom = abs(y - box.bottom) <= handle_radius_video

        if self._lock_aspect.get():
            if near_left and near_top:
                return "top_left"
            if near_right and near_top:
                return "top_right"
            if near_left and near_bottom:
                return "bottom_left"
            if near_right and near_bottom:
                return "bottom_right"
        else:
            if near_left and box.top <= y <= box.bottom:
                return "left"
            if near_right and box.top <= y <= box.bottom:
                return "right"
            if near_top and box.left <= x <= box.right:
                return "top"
            if near_bottom and box.left <= x <= box.right:
                return "bottom"

        if box.left <= x <= box.right and box.top <= y <= box.bottom:
            return "move"

        return None

    def _resize_crop_box_by_handle(self, start: CropBox, handle: str, dx: int, dy: int) -> CropBox:
        if handle in {"top_left", "top_right", "bottom_left", "bottom_right"}:
            return self._resize_crop_box_by_corner_keep_aspect(start, handle, dx, dy)

        left = start.left
        top = start.top
        width = start.width
        height = start.height

        if handle == "left":
            left = start.left + dx
            width = start.right - left
        elif handle == "right":
            width = start.width + dx
        elif handle == "top":
            top = start.top + dy
            height = start.bottom - top
        elif handle == "bottom":
            height = start.height + dy

        if width < self.MIN_CROP_SIZE:
            if handle == "left":
                left = start.right - self.MIN_CROP_SIZE
            width = self.MIN_CROP_SIZE

        if height < self.MIN_CROP_SIZE:
            if handle == "top":
                top = start.bottom - self.MIN_CROP_SIZE
            height = self.MIN_CROP_SIZE

        return CropBox(left, top, width, height)

    def _resize_crop_box_by_corner_keep_aspect(self, start: CropBox, handle: str, dx: int, dy: int) -> CropBox:
        aspect = start.aspect_ratio if start.aspect_ratio > 0 else 1.0

        if handle == "top_left":
            anchor_x, anchor_y = start.right, start.bottom
            raw_w = start.width - dx
            raw_h = start.height - dy
            sign_x, sign_y = -1, -1
        elif handle == "top_right":
            anchor_x, anchor_y = start.left, start.bottom
            raw_w = start.width + dx
            raw_h = start.height - dy
            sign_x, sign_y = 1, -1
        elif handle == "bottom_left":
            anchor_x, anchor_y = start.right, start.top
            raw_w = start.width - dx
            raw_h = start.height + dy
            sign_x, sign_y = -1, 1
        else:  # bottom_right
            anchor_x, anchor_y = start.left, start.top
            raw_w = start.width + dx
            raw_h = start.height + dy
            sign_x, sign_y = 1, 1

        raw_w = max(self.MIN_CROP_SIZE, raw_w)
        raw_h = max(self.MIN_CROP_SIZE, raw_h)

        # Use the stronger mouse movement while preserving the existing aspect ratio.
        width_from_h = raw_h * aspect
        if abs(raw_w - start.width) >= abs(width_from_h - start.width):
            new_w = int(round(raw_w))
            new_h = int(round(new_w / aspect))
        else:
            new_h = int(round(raw_h))
            new_w = int(round(new_h * aspect))

        new_w = max(self.MIN_CROP_SIZE, new_w)
        new_h = max(self.MIN_CROP_SIZE, new_h)

        if sign_x < 0:
            left = anchor_x - new_w
        else:
            left = anchor_x

        if sign_y < 0:
            top = anchor_y - new_h
        else:
            top = anchor_y

        return CropBox(left, top, new_w, new_h)

    def _redraw(self) -> None:
        self.canvas.delete("all")

        if self._last_frame_for_display_bgr is None:
            return

        frame_bgr = self._last_frame_for_display_bgr
        frame_h, frame_w = frame_bgr.shape[:2]
        canvas_w = max(1, self.canvas.winfo_width())
        canvas_h = max(1, self.canvas.winfo_height())

        scale = min(canvas_w / frame_w, canvas_h / frame_h)
        display_w = max(1, int(round(frame_w * scale)))
        display_h = max(1, int(round(frame_h * scale)))
        offset_x = (canvas_w - display_w) // 2
        offset_y = (canvas_h - display_h) // 2

        self._display_scale = scale
        self._display_offset_x = offset_x
        self._display_offset_y = offset_y
        self._display_width = display_w
        self._display_height = display_h

        rgb = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGB)
        pil_image = Image.fromarray(rgb).resize((display_w, display_h), Image.Resampling.LANCZOS)
        self._tk_image = ImageTk.PhotoImage(pil_image)

        self.canvas.create_image(offset_x, offset_y, image=self._tk_image, anchor="nw")

        if self._crop_enabled.get() and self._crop_box is not None:
            self._draw_crop_overlay()

    def _draw_crop_overlay(self) -> None:
        if self._crop_box is None:
            return

        box = self._crop_box
        x1, y1 = self._video_to_screen(box.left, box.top)
        x2, y2 = self._video_to_screen(box.right, box.bottom)

        self.canvas.create_rectangle(x1, y1, x2, y2, outline=self.CROP_COLOR, width=2)

        if self._lock_aspect.get():
            handles = [
                ((x1, y1), "top_left"),
                ((x2, y1), "top_right"),
                ((x1, y2), "bottom_left"),
                ((x2, y2), "bottom_right"),
            ]
        else:
            handles = [
                ((x1, (y1 + y2) // 2), "left"),
                ((x2, (y1 + y2) // 2), "right"),
                (((x1 + x2) // 2, y1), "top"),
                (((x1 + x2) // 2, y2), "bottom"),
            ]

        r = self.HANDLE_SIZE_SCREEN // 2
        for (hx, hy), _name in handles:
            self.canvas.create_rectangle(hx - r, hy - r, hx + r, hy + r, fill=self.CROP_COLOR, outline="black")

    def _update_status(self) -> None:
        if self._num_frames <= 0:
            self.status_text.set("No video loaded")
            self.crop_text.set("Crop: -")
            return

        input_fps_text = f"{self._input_fps:.2f}" if self._input_fps else "?"
        target_fps_text = str(self._target_fps) if self._target_fps else "?"
        self.status_text.set(
            f"Frame {self._current_frame_index} / {self._num_frames - 1} | "
            f"Start {self._start_frame} | End {self._end_frame} | "
            f"Input FPS {input_fps_text} | Target FPS {target_fps_text} | Frame skip {self._frame_skip}"
        )

        if not self._crop_enabled.get() or self._crop_box is None:
            self.crop_text.set("Crop: disabled")
        else:
            box = self._crop_box
            self.crop_text.set(
                f"Crop: left={box.left}, top={box.top}, width={box.width}, height={box.height}, "
                f"aspect={box.aspect_ratio:.2f}"
            )

    def _save_current_frame(self):
        if self._video_path is None or self._last_frame_bgr is None:
            messagebox.showinfo("No video", "Open a video first.")
            return

        digits = max(1, len(str(max(self._num_frames - 1, 0))))
        base_name = self._video_path.stem

        frame_image, was_cropped = frame_bgr = self._apply_crop_if_needed(self._player.get_next_frame())

        out_name = f"{base_name}_{self._current_frame_index:0{digits}d}{'_cropped' if was_cropped else ''}.jpg"
        out_path = self._video_path.parent / out_name

        jpg_quality = 95

        write_ok = cv2.imwrite(
            str(out_path),
            frame_image,
            [cv2.IMWRITE_JPEG_QUALITY, jpg_quality],
        )
        if write_ok:
            messagebox.showinfo("Frame Saved", f"Saved frame to: {out_path}")
        else:
            raise RuntimeError(f"Could not write file: {out_path}")

    def _save_as(self) -> None:
        if self._video_path is None or self._last_frame_bgr is None:
            messagebox.showinfo("No video", "Open a video first.")
            return

        if self._exporting:
            return

        ext = self._settings.recorder.file_ext
        ext = ext if str(ext).startswith(".") else f".{ext}"

        initial_name = f"{self._video_path.stem}_export{ext}"
        chosen = filedialog.asksaveasfilename(
            title="Save video as",
            initialdir=str(self._video_path.parent),
            initialfile=initial_name,
            defaultextension=ext,
            filetypes=[(f"Video {ext}", f"*{ext}"), ("All files", "*.*")],
        )
        if not chosen:
            return

        output_path = Path(chosen)
        output_path = output_path.with_suffix(ext)

        try:
            self._export_video(output_path)
            messagebox.showinfo("Export finished", f"Saved:\n{output_path}")
        except Exception as exc:
            messagebox.showerror("Export failed", str(exc))
        finally:
            self._exporting = False

    def _export_video(self, output_path: Path) -> None:
        if self._video_path is None:
            return

        self._pause()
        self._exporting = True
        self.update_idletasks()

        output_dir = output_path.parent
        output_name_without_extension = output_path.stem

        export_player = VideoPlayer(self._video_path, target_fps=self._target_fps)
        recorder = VideoRecorder(
            FPS=int(self._target_fps or self._input_fps or 25),
            output_path=output_dir,
            settings=self._settings.recorder,
        )

        try:
            export_player.set_current_frame_index(self._start_frame)
            actual_path = recorder.start_recording(output_name_without_extension)
            if actual_path is None:
                raise RuntimeError("Recorder is already recording.")

            frame_index = self._start_frame
            while frame_index <= self._end_frame:
                frame_bgr = export_player.get_next_frame()
                if frame_bgr is None:
                    break

                frame_bgr, _ = self._apply_crop_if_needed(frame_bgr)
                frame = Frame(
                    image=frame_bgr,
                    frame_type=Frame.FrameType.COLOR,
                    image_size=(frame_bgr.shape[1], frame_bgr.shape[0]),
                )
                recorder.put_image(frame)

                frame_index += self._frame_skip
                if frame_index <= self._end_frame:
                    export_player.set_current_frame_index(frame_index)

                self.status_text.set(f"Exporting frame {min(frame_index, self._end_frame)} / {self._end_frame}")
                self.update_idletasks()

        finally:
            recorder.stop_recording()
            export_player.close()
            self._update_status()

    def _apply_crop_if_needed(self, frame_bgr: BGRImage) -> (BGRImage, bool):
        if not self._crop_enabled.get() or self._crop_box is None:
            return frame_bgr, False

        box = self._clamp_crop_box_for_shape(self._crop_box, frame_bgr.shape[:2])
        return frame_bgr[box.top:box.bottom, box.left:box.right].copy(), True

    def _clamp_crop_box_for_shape(self, box: CropBox, shape_hw: tuple[int, int]) -> CropBox:
        frame_h, frame_w = shape_hw
        width = max(self.MIN_CROP_SIZE, min(box.width, frame_w))
        height = max(self.MIN_CROP_SIZE, min(box.height, frame_h))
        left = max(0, min(box.left, frame_w - width))
        top = max(0, min(box.top, frame_h - height))
        return CropBox(left, top, width, height)

    def destroy(self) -> None:
        self._pause()
        self._close_player()
        super().destroy()


if __name__ == "__main__":
    app = VideoCropExportGui()
    app.mainloop()
