# Code base generated by Mistral (manual adjustments/extensions)
"""
Tool: Process input images (video frames) and generate a background
      image using the median method and MOG2 ('removal' of dynamic objects)

Usage:
- Start this script and select a video file from the file open dialog
- Open the file and wait until the data is processed
- The results will be stored in the data folder (result filenames will be the video file name + a suffix)
"""
from pathlib import Path

import cv2
import numpy as np
from tkinter import filedialog

from bird_guard.main import APP_NAME
from bird_guard.utils import PlatformInfo
from bird_guard.utils import VideoPlayer

DATA_PATH = PlatformInfo.get_data_path(APP_NAME)

# Input image dir
IMAGE_DIR = DATA_PATH / "dummy_cam_data"

# Choose video file
file_path = filedialog.askopenfilename(
    title="Open Video",
    filetypes=[("All Files", "*.*"), ("Videos", "*.avi *.mp4")],
    initialdir=IMAGE_DIR
)

if not file_path:
    exit()

input_file = Path(file_path)

# Result images
output_file_median = IMAGE_DIR / f"{input_file.stem}_background_median.jpg"
output_file_MOG2   = IMAGE_DIR / f"{input_file.stem}_background_MOG2.jpg"

# -------------

print("Gathering frame images ...")
video_player = VideoPlayer(input_file)
images = [video_player.get_next_frame() for _ in range(video_player.get_num_frames())]

print("Generating median image ...")
median_background = np.median(images, axis=0).astype("uint8")
cv2.imwrite(output_file_median, median_background)
print(f"Saved median result to: {output_file_median}")


print("Generating MOG2 image ...")
back_sub = cv2.createBackgroundSubtractorMOG2(history=500, varThreshold=32, detectShadows=False)

background = None

for frame in images:

    fg_mask = back_sub.apply(frame)

    if background is None:
        background = frame.copy().astype(float)
    else:
        background = cv2.accumulateWeighted(frame.astype(float), background, alpha=0.01)

cv2.imwrite(output_file_MOG2, background.astype("uint8"))
print(f"Saved MOG2 result to: {output_file_MOG2}")

print("FINISHED")