# Code generated by ChatGPT (using bird_guard classes)
"""
Tool: TKinter GUI to record mp4 videos with the Picamera2 implementation

Usage:
- On startup, config.toml is read automatically and parameters are pre-filled accordingly
- Change settings (fps, image size), if required
- Choose image source: COLOR or LORES (grayscale)
- Consider changing the output directory
- Click "Start camera" to start up the Picamera2 -> a live view should become visible in the GUI
- Click "Start rec" to start the recording (output file and recording duration are shown below the live view image)
- Click "Stop rec" to stop the recording and write the video file
"""

from __future__ import annotations

import threading
import time
from datetime import datetime
from pathlib import Path
from tkinter import Tk, Button, Label, StringVar, IntVar, BooleanVar, filedialog, ttk

import cv2
from PIL import Image as PILImage, ImageTk

from bird_guard.config import ConfigHandler
from bird_guard.utils import PlatformInfo, FPSTiming
from bird_guard.camera.camera import PiCam2Camera, Frame, DummyCamera
from bird_guard.vision.utils.vision_utils import VisionUtils
from bird_guard.vision.utils.image_utils import ImageUtils
from bird_guard.recorder import VideoRecorder, Config_VideoRecorder


APP_NAME = "bird_guard"
PREVIEW_SIZE = (960, 540)


def frame_to_cv_image(frame: Frame, frame_type: Frame.FrameType):

    if frame_type == Frame.FrameType.LORES:
        return cv2.cvtColor(frame.data, cv2.COLOR_YUV2BGR_I420)

    if hasattr(frame, "data"):
        return frame.data

    raise RuntimeError("Could not extract image from Frame. Adapt frame_to_cv_image().")


def ensure_bgr(image):
    if len(image.shape) == 2:
        return cv2.cvtColor(image, cv2.COLOR_GRAY2BGR)

    if image.shape[2] == 4:
        return cv2.cvtColor(image, cv2.COLOR_BGRA2BGR)

    if image.shape[2] == 3:
        return image

    raise RuntimeError(f"Unsupported image shape: {image.shape}")


def cv_to_tk_image(image):
    """
    Convert cv2 image to Tk image.
    """
    if len(image.shape) == 2:
        rgb = cv2.cvtColor(image, cv2.COLOR_GRAY2RGB)
    else:
        rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    pil = PILImage.fromarray(rgb)
    return ImageTk.PhotoImage(pil)


class VideoRecorderGui:
    def __init__(self):
        self.root = Tk()
        self.root.title("Bird Guard Video Recorder")
        self.root.geometry("1120x720")
        self.root.resizable(False, False)

        config_path = PlatformInfo.get_config_path(APP_NAME) / "config.toml"
        self.settings = ConfigHandler(config_path).get_config()

        self.recording_dir = PlatformInfo.get_data_path(APP_NAME) / "recordings"
        self.recording_dir.mkdir(parents=True, exist_ok=True)

        self.camera: PiCam2Camera | None = None
        self.running = False
        self.recording = False
        self.worker_thread: threading.Thread | None = None
        self.video_recorder: VideoRecorder | None = None
        self.current_recording_path: Path | None = None
        self.recording_start_time: float | None = None

        self.path_status_var = StringVar(value=f"Output directory: {self.recording_dir}")
        self.recording_status_var = StringVar(value="No recording")

        self.fps_var = IntVar(value=self.settings.camera.fps)
        self.frame_type_var = StringVar(value="LORES")
        self.lores_w_var = IntVar(value=self.settings.camera.lores_image_size[0])
        self.lores_h_var = IntVar(value=self.settings.camera.lores_image_size[1])
        self.color_w_var = IntVar(value=self.settings.camera.color_image_size[0])
        self.color_h_var = IntVar(value=self.settings.camera.color_image_size[1])
        self.recording_dir_var = StringVar(value=str(self.recording_dir))
        self.status_var = StringVar(value="Idle")

        self.latest_preview = None
        self.preview_label = Label(self.root)
        self.preview_label.place(x=20, y=20, width=PREVIEW_SIZE[0], height=PREVIEW_SIZE[1])

        self.build_controls()

        self.root.protocol("WM_DELETE_WINDOW", self.close)

    def build_controls(self):
        x = 1000

        Label(self.root, text="FPS").place(x=x, y=30)
        ttk.Spinbox(self.root, from_=1, to=60, textvariable=self.fps_var, width=8).place(x=x, y=55)

        Label(self.root, text="Frame").place(x=x, y=95)
        ttk.Combobox(
            self.root,
            textvariable=self.frame_type_var,
            values=["LORES", "COLOR"],
            width=10,
            state="readonly",
        ).place(x=x, y=120)

        Label(self.root, text="LORES W/H").place(x=x, y=165)
        ttk.Spinbox(self.root, from_=160, to=3840, textvariable=self.lores_w_var, width=8).place(x=x, y=190)
        ttk.Spinbox(self.root, from_=120, to=2160, textvariable=self.lores_h_var, width=8).place(x=x, y=220)

        Label(self.root, text="COLOR W/H").place(x=x, y=265)
        ttk.Spinbox(self.root, from_=160, to=3840, textvariable=self.color_w_var, width=8).place(x=x, y=290)
        ttk.Spinbox(self.root, from_=120, to=2160, textvariable=self.color_h_var, width=8).place(x=x, y=320)

        Button(self.root, text="Start camera", command=self.start_camera).place(x=x, y=420, width=90)
        Button(self.root, text="Start rec", command=self.start_recording).place(x=x, y=470, width=90)
        Button(self.root, text="Stop rec", command=self.stop_recording).place(x=x, y=520, width=90)

        Label(self.root, textvariable=self.status_var, wraplength=100).place(x=x, y=580)

        status_y = 575
        Label(
            self.root,
            textvariable=self.path_status_var,
            anchor="w",
        ).place(x=20, y=status_y, width=820, height=25)

        Button(
            self.root,
            text="Choose output dir",
            command=self.choose_recording_dir,
        ).place(x=850, y=status_y, width=130, height=25)

        Label(
            self.root,
            textvariable=self.recording_status_var,
            anchor="w",
        ).place(x=20, y=status_y + 30, width=960, height=25)

    def choose_recording_dir(self):
        path = filedialog.askdirectory(initialdir=str(self.recording_dir))
        if path:
            self.recording_dir = Path(path)
            self.recording_dir.mkdir(parents=True, exist_ok=True)
            self.recording_dir_var.set(str(self.recording_dir))
            self.path_status_var.set(f"Directory: {self.recording_dir}")

    def get_frame_type(self):
        return Frame.FrameType.LORES if self.frame_type_var.get() == "LORES" else Frame.FrameType.COLOR

    def apply_camera_settings(self):
        """
        Adjust this if your settings object is immutable or has different field names.
        """
        self.settings.camera.fps = int(self.fps_var.get())
        self.settings.camera.lores_resolution = (
            int(self.lores_w_var.get()),
            int(self.lores_h_var.get()),
        )
        self.settings.camera.color_resolution = (
            int(self.color_w_var.get()),
            int(self.color_h_var.get()),
        )

    def start_camera(self):
        if self.running:
            return

        self.apply_camera_settings()

        match PlatformInfo.get_platform():
            case PlatformInfo.OperatingSystem.PROBABLY_RASPI:
                print("Detected OS is likely Raspi -> Using Picamera2!")
                self.camera = PiCam2Camera(self.settings.camera)
            case PlatformInfo.OperatingSystem.WINDOWS | PlatformInfo.OperatingSystem.LINUX:
                print("Detected OS is non-Raspi -> Using dummy camera!")
                self.camera = DummyCamera(self.settings.camera, APP_NAME)
            case _:
                raise NotImplementedError(f"Platform {PlatformInfo.get_platform_name()} is not supported.")

        self.running = True
        self.worker_thread = threading.Thread(target=self.capture_loop, daemon=True)
        self.worker_thread.start()
        self.status_var.set("Camera running")

    def start_recording(self):
        if not self.running:
            self.start_camera()

        if self.recording:
            return

        fps = int(self.fps_var.get())

        settings = Config_VideoRecorder(
            enable=True,
            history_seconds=0,
        )

        self.video_recorder = VideoRecorder(
            FPS=fps,
            output_path=self.recording_dir,
            settings=settings,
        )

        output_file = self.video_recorder.start_recording()

        self.recording = True
        self.recording_start_time = time.monotonic()
        self.current_recording_path = Path(output_file)

        self.status_var.set("Recording")
        self.recording_status_var.set(f"Recording to: {self.current_recording_path.name}")

    def stop_recording(self):
        self.recording = False

        saved_path = self.current_recording_path

        if self.video_recorder is not None:
            self.video_recorder.stop_recording()
            self.video_recorder = None

        if saved_path is not None:
            self.current_recording_path = saved_path
            print(f"Saved recording: {saved_path}")
            self.recording_status_var.set(f"Saved: {self.current_recording_path.name}")
        else:
            self.recording_status_var.set("Recording stopped, no video saved")

        self.recording_start_time = None
        self.status_var.set("Recording stopped")

    def capture_loop(self):
        fps_timing = FPSTiming(1.0 / int(self.fps_var.get()))

        while self.running:
            fps_timing.start_measurement()

            try:
                frame_type = self.get_frame_type()
                frame = self.camera.get_frame(frame_type)
                image = frame_to_cv_image(frame, frame_type)

                preview = ImageUtils.rescale(image, PREVIEW_SIZE)
                self.latest_preview = cv_to_tk_image(preview)

                self.root.after(0, self.update_preview)

                if self.recording and self.video_recorder is not None:
                    self.video_recorder.put_image(frame)

            except Exception as exc:
                self.status_var.set(f"Error: {exc}")

            fps_timing.wait_remaining_time()

    def update_preview(self):
        if self.latest_preview is not None:
            self.preview_label.configure(image=self.latest_preview)
            self.preview_label.image = self.latest_preview

        if self.recording and self.recording_start_time is not None and self.current_recording_path is not None:
            elapsed = int(time.monotonic() - self.recording_start_time)
            minutes = elapsed // 60
            seconds = elapsed % 60
            self.recording_status_var.set(
                f"Recording: {self.current_recording_path.name} | {minutes:02d}:{seconds:02d}"
            )

    def close(self):
        self.running = False
        self.stop_recording()

        if self.worker_thread is not None:
            self.worker_thread.join(timeout=1.0)

        if self.camera is not None and hasattr(self.camera, "close"):
            self.camera.close()

        self.root.destroy()

    def run(self):
        self.root.mainloop()


def main():
    VideoRecorderGui().run()


if __name__ == "__main__":
    main()
